### ISSUE TITLE
output smaller object?

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/geex#43]
I haven't got out the tape measurer, but a geex object seems to be often quite large. 

The easiest way to reduce the output is to save the desired output (`@vcov` and `@estimates` slots) to a new list object, and then remove/delete the original s4 object.

Is is there a s4 class for, say, `geex_ests`? For just the `vcov` and `estimates` slots? 

Or is there a way to request that geex doesn't output say `@call`, `@basis`, etc?
(fwiw, "no" is an acceptable answer)

**Comment by bsaul** [comment]
We definitely want to keep the @call, but the memory stuff is the A_i and
B_i matrices and the original data. Maybe we add a `keep_intermediates`
option that keeps these objects or not.


On February 27, 2018 at 10:32:46 AM, Brian G. Barkley (
notifications@github.com) wrote:

I haven't got out the tape measurer, but a geex object seems to be often
quite large.

The easiest way to reduce the output is to save the desired output (@vcov
and @estimates slots) to a new list object, and then remove/delete the
original s4 object.

Is is there a s4 class for, say, geex_ests? For just the vcov and estimates
slots?

Or is there a way to request that geex doesn't output say @call, @basis,
etc?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bsaul/geex/issues/43>, or mute the thread

**Comment by bsaul** [comment]
Brian,
I think I will implement this by adding a `summary()` method.

**Comment by bsaul** [comment]
I added a `geex-summary` and `summary()` method or the Class `geex` (output of `m_estimate()`). `summary()` has two options `keep_data` and `keep_args`, setting both of these to `FALSE` will dramatically lighten the load.
